services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    contao.cron.fernschach_mitgliedschaftscheck:
        class: Schachbulle\ContaoFernschachBundle\Cron\Mitgliedschaftscheck
        arguments:
            - '@contao.framework'

    contao.cron.fernschach_mitgliedschaftsende:
        class: Schachbulle\ContaoFernschachBundle\Cron\Mitgliedschaftsende
        arguments:
            - '@contao.framework'

    contao.cron.fernschach_mitgliederpruefung:
        class: Schachbulle\ContaoFernschachBundle\Cron\Mitgliederpruefung
        arguments:
            - '@contao.framework'

    contao.cron.fernschach_nenngeld:
        class: Schachbulle\ContaoFernschachBundle\Cron\Nenngeld
        arguments:
            - '@contao.framework'

    contao.cron.fernschach_streichung:
        class: Schachbulle\ContaoFernschachBundle\Cron\Streichung
        arguments:
            - '@contao.framework'
